steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/project-c736b433-1b47-40c0-a2c/petclub-repo/petclub-backend:$COMMIT_SHA'
      - '-t'
      - 'us-central1-docker.pkg.dev/project-c736b433-1b47-40c0-a2c/petclub-repo/petclub-backend:latest'
      - '.'

  # Push both tags
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '--all-tags'
      - 'us-central1-docker.pkg.dev/project-c736b433-1b47-40c0-a2c/petclub-repo/petclub-backend'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'petclub-backend'
      - '--image'
      - 'us-central1-docker.pkg.dev/project-c736b433-1b47-40c0-a2c/petclub-repo/petclub-backend:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--quiet'

images:
  - 'us-central1-docker.pkg.dev/project-c736b433-1b47-40c0-a2c/petclub-repo/petclub-backend'

options:
  logging: CLOUD_LOGGING_ONLY
